### ISSUE TITLE
[Question] About Grouped-Query Attention code on model.py 

### ISSUE THREAD

**Issue by doammii** [Fraunhofer-SCAI/llamol#2]
Hello,

I have a question about LlaMol [**llamol/model.py**](https://github.com/Fraunhofer-SCAI/llamol/blob/main/model.py) code.
```python
# line 150-152(forward function): grouped multiquery attention - expand out keys and values
        xk = repeat_kv(xk, self.n_rep)  # (bs, seqlen, n_local_heads, head_dim)
        xv = repeat_kv(xv, self.n_rep)  # (bs, seqlen, n_local_heads, head_dim)

# line 270-272(forward_with_kvcache function): grouped multiquery attention - expand out keys and values
        xk = repeat_kv(xk, self.n_rep)  # (bs, seqlen, n_local_heads, head_dim)
        xv = repeat_kv(xv, self.n_rep)  # (bs, seqlen, n_local_heads, head_dim)
``` 

 According to the [LlaMol paper](https://arxiv.org/abs/2311.14407), you opted 'full multi-head attention mechanism', unlike the original Llama2 architecture that used Grouped-Query Attention. 
 However, as attached to the code block above, I was able to confirm that Grouped-Query Attention is implemented on model.py. 
 I wonder **what role the above Grouped-Query Attention code part plays in the mechanism of the whole model and why it is needed**.

Thank you for reading this issue.

**Comment by NiklasDo** [comment]
In the code is still the mechanism to implement the Grouped-Query Attention, however self.n_rep is always 1 in our case. So this line does essentially nothing. You would have to adjust the `model_parallel_size = 1` in the Attention-class to something > 1.
If you look in the function, repeat_kv you can see this also:
```python
def repeat_kv(x: torch.Tensor, n_rep: int) -> torch.Tensor:
    """torch.repeat_interleave(x, dim=2, repeats=n_rep)"""
    bs, slen, n_kv_heads, head_dim = x.shape
    if n_rep == 1:
        return x <--- Here it shortcuts
    return (
        x[:, :, :, None, :]
        .expand(bs, slen, n_kv_heads, n_rep, head_dim)
        .reshape(bs, slen, n_kv_heads * n_rep, head_dim)
    )
```

Hope this helps!

**Comment by doammii** [comment]
Thank you so much for your kind reply.
